project-a-09-main/login/urls.py
from django.urls import path

from . import views
from .views import google_login
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = "login"

urlpatterns = [
    path("", views.welcome_page, name="welcome"),
    path("login/", views.login, name="login"),
    path("home/", views.home, name="home"),
    path("<int:report_id>/submission", views.see_submission, name="submission"),
    path('google-login/', google_login, name='google_login'),
    path('accounts/', include('allauth.urls')),
    path('logout/', views.logout_view, name='logout'),
    path('<int:report_id>/resolve_report', views.resolve_report, name='resolve_report'),
    path('update_notes/', views.update_notes, name='update_notes'),
    path('view_reports/', views.view_reports, name='view_reports'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project-a-09-main/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("login.urls")),
    path("login/", include("login.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

project-a-09-main/login/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class User(models.Model):
    # this can be changed by a Django admin, everyone defaulted to False for being a site admin
    is_admin = models.BooleanField(default=False)
    # adding in this email field, so we can check the email from Google and grab the registered user associated
    # with this email (to see if they're an admin)
    email = models.EmailField(max_length = 254, blank=True,unique=True)
    username = models.CharField(max_length = 150)
    #later add in a foreign key reference to reports, so a user's reports are stored

    def __str__(self):
        return self.username

    def get_reports(self):
        # purpose: since foreign key isn't working well for anonymous reports...
        # when you are trying to load a user's reports, see which reports' usernames match this username
        reports = Report.objects.filter(username__exact=self.username)
        if reports.count() == 0:
            return None
        else:
            return reports


# COMMENTING OUT FOR POSSIBLE LATER USE - Joe
# class Report (models.Model):
    # # an admin marks a report as resolved, maybe with a checkbox
    # resolved = models.BooleanField(default=False)
    # # this is the user that submitted the report (TODO how to represent this is anonymous)
    # user = models.ForeignKey(User, on_delete=models.CASCADE, default = None)
    # # this is a placeholder, we will need to add more fields
    # #problem_text = models.CharField(max_length = 400)

    # # need to add more form fields, file savers?

    # def __str__(self):
    #     if self.user:
    #         return "Report " + str(self.id) + "- user: " + self.user.username + ", resolved: " + str(self.resolved)
    #     else:
    #         return "Report " + str(self.id) + "- (anonymous), resolved: " + str(self.resolved)

class Report(models.Model):

    ## Megan added - from OG model
    username = models.CharField(max_length=150, default="(anonymous)")
    resolved = models.BooleanField(default=False)
    notes = models.TextField(default='', blank=True, verbose_name = "Administrator Notes")

    # from form
    full_name = models.CharField(max_length=200, default = '')
    incident_type = models.CharField(max_length=50, default = '')
    description = models.TextField(default = '', blank = True)
    location = models.CharField(max_length=500, default = '', blank = True)
    images = models.ImageField(upload_to='report_images/', default = '', blank = True)
    videos = models.FileField(upload_to='report_videos/', default = '', blank = True)
    submission_date = models.DateTimeField(default = timezone.now)

    #Statuses
    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_CHOICES = [
        (STATUS_NEW, 'New'),
        (STATUS_IN_PROGRESS, 'In Progress'),
    ]

    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default=STATUS_NEW,
    )

    def __str__(self):
        incident_selection = ""
        if self.incident_type == "1":
            incident_selection = "Security Breach"
        elif self.incident_type == "2":
            incident_selection = "Physical Altercation"
        elif self.incident_type == "3":
            incident_selection = "Theft or Vandalism"
        elif self.incident_type == "4":
            incident_selection = "Harassment or Discrimination"
        elif self.incident_type == "5":
            incident_selection = "Accident or Injury"
        elif self.incident_type == "6":
            incident_selection = "Medical Emergency"
        elif self.incident_type == "7":
            incident_selection = "Fire or Hazardous Materials Incident"
        elif self.incident_type == "8":
            "Cybersecurity Incident"
        elif self.incident_type == "9":
            incident_selection = "Missing Person"
        else:
            incident_selection = "Suspicious Activity"
        return incident_selection + ", location: " + self.location

project-a-09-main/login/forms.py
from django import forms
 
class InputForm(forms.Form):
 
    full_name = forms.CharField(max_length = 200)
    options = (
    ("1", "Security Breach"),
    ("2", "Physical Altercation"),
    ("3", "Theft or Vandalism"),
    ("4", "Harassment or Discrimination"),
    ("5", "Accident or Injury"),
    ("6", "Medical Emergency"),
    ("7", "Fire or Hazardous Materials Incident"),
    ("8", "Cybersecurity Incident"),
    ("9", "Missing Person"),
    ("10", "Suspicious Activity")
    )
    incident_type = forms.ChoiceField(widget=forms.Select, choices = options)
    description = forms.CharField(max_length = 1000,required=False)
    location = forms.CharField(max_length = 500,required=False)
    images = forms.ImageField(required=False)
    videos = forms.FileField( required=False)

project-a-09-main/login/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import User, Report
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from allauth.socialaccount.views import RedirectAuthenticatedUserMixin
from django.urls import reverse_lazy, reverse
from django.contrib.auth import logout
from .forms import InputForm
from .models import Report
from django.contrib.auth.decorators import login_required


def google_login(request):
    return redirect(reverse_lazy('login:welcome'))

def login(request):
    return render(request, "login/login_page.html")
    # return HttpResponse("this will be the login page")

def welcome_page(request):
    return render(request, "login/welcome_page.html")


@login_required
def view_reports(request):
    # Fetch the currently logged-in user
    curr_user = request.user

    # Retrieve the reports submitted by the current user
    user_reports = Report.objects.filter(username=curr_user.username)

    # Pass the user_reports to the template for rendering
    context = {
        'user_reports': user_reports
    }

    return render(request, "login/view_reports.html", context)

# update to pass the user
def home(request):
    load_admin = False
    curr_username = "DEFAULT123"
    curr_user = None

    try:
        login_email = request.user.email
        is_defined_user = User.objects.filter(email=login_email).exists()

        if not is_defined_user:
            user = User(email=login_email, username=request.user.username)
            user.save()
        else:
            curr_username = User.objects.get(email=login_email).username
            curr_user = User.objects.get(email=login_email)
            if User.objects.get(email=login_email).is_admin:
                load_admin = True
    finally:
        if load_admin:
            context = {
                "all_reports": Report.objects.all(),
                "resolved_reports": Report.objects.filter(resolved=True),
                "unresolved_reports": Report.objects.filter(resolved=False),
            }
            return render(request, "login/admin_home.html", context)
        else:
            user_reports = curr_user.get_reports() if curr_user else None  # Retrieve user's previous submissions
            if request.method == 'POST':
                form = InputForm(request.POST, request.FILES)
                if form.is_valid():
                    set_username = curr_username if curr_username != "DEFAULT123" else "(anonymous)"
                    report = Report(
                        username=set_username,
                        full_name=form.cleaned_data['full_name'],
                        incident_type=form.cleaned_data['incident_type'],
                        description=form.cleaned_data['description'],
                        location=form.cleaned_data['location'],
                        images=form.cleaned_data['images'],
                        videos=form.cleaned_data['videos']
                    )
                    report.save()
                    return HttpResponseRedirect(reverse("login:submission", args=(report.id,)))
                form = InputForm()
                return render(request, "login/home_page.html", {'form': form, 'user_reports': user_reports})
            else:
                form = InputForm()
                return render(request, "login/home_page.html", {'form': form, 'user_reports': user_reports})


def logout_view(request):
    logout(request)
    return redirect("/login")

def see_submission(request, report_id):
    # Get the report, or 404 if not found
    report = get_object_or_404(Report, pk=report_id)

    # Assume the user is not an admin until verified
    is_admin = False

    # Check if the user is logged in
    if request.user.is_authenticated:
        # Check if there's a User entry for the current logged-in user's email
        logged_in_user = User.objects.filter(email=request.user.email).first()
        if logged_in_user:
            is_admin = logged_in_user.is_admin

            # If the user is an admin and the report is 'new', update status to 'in_progress'
            if is_admin and report.status == 'new':
                report.status = 'in_progress'
                report.save()

    context = {
        "report": report,
        "is_admin": is_admin
    }
    return render(request, "login/view_submission.html", context)


def resolve_report(request, report_id):
    report = get_object_or_404(Report, pk=report_id)
    report.resolved = True
    report.save()
    return redirect(reverse_lazy('login:home'))


def update_notes(request):
    if request.method == 'POST':
        report_id = request.POST.get('report_id')
        new_notes = request.POST.get('notes')

        # Retrieve the report object
        report = get_object_or_404(Report, id=report_id)

        # Update the notes field
        report.notes = new_notes

        # Save the changes to the database
        report.save()

    # Redirect back to the admin home page
    return redirect('login:home')

project-a-09-main/login/templates/login/admin_home.html
{% extends "base.html" %}

{% load bootstrap5 %}
{% load socialaccount %}

{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}


<body>
    <h1>UVA Reportify Site Admin Home</h1>

    <div>
      {% if user.is_authenticated %}
          <p>You are signed in as a SITE ADMIN: {{ user.username }}</p>

        {% endif %}
    </div>
    <div style="margin-top: 20px">

        {% if all_reports %}
            <h3 style="margin-bottom: 20px; margin-top: 40px">View Submitted Reports</h3>

             <div class="accordion" id="reportAccordion">
              <div class="accordion-item">
                <h2 class="accordion-header" id="headingUnresolved">
                  <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Unresolved Reports
                  </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingUnresolved" data-bs-parent="#reportAccordion">
                  <div class="accordion-body">
                      <table class="table table-hover">
                        <tr>
                            <th>Report Number</th>
                            <th>User</th>
                            <th>Report Status</th>
                            <th>Summary</th>
                            <th>View Submission</th>
                            <th>Administrator Notes</th>
                        </tr>
                        {% for report in unresolved_reports %}
                                <tr>
                                    <td>{{ report.id }}</td>
                                    <td>{{ report.username }}</td>
                                    <td>
                                        {% if report.status == 'new' %}
                                            New
                                        {% elif report.status == 'in_progress' %}
                                            In Progress
                                        {% endif %}
                                    </td>
                                    <td>{{ report }}</td>
                                    <td>
                                        <a href="{% url "login:submission" report.id %}">
                                            <button class="btn btn-outline-primary">
                                                View submission
                                            </button>
                                        </a>
                                    </td>
                                     <td>
                                        <form method="post" action="{% url 'login:update_notes' %}" class="notes-form">
                                            {% csrf_token %}
                                            <div class="flex-container">
                                                <input type="hidden" name="report_id" value="{{ report.id }}">
                                                <textarea class="form-control editable-notes" name="notes" rows="3">{{ report.notes }}</textarea>
                                                <button type="submit" class="btn btn-outline-success btn-sm mt-2" style="width: 100%">Save</button>
                                            </div>
                                        </form>

                                    </td>
                                </tr>
                        {% endfor %}
                    </table>
                  </div>
                </div>
              </div>
              <div class="accordion-item">
                <h2 class="accordion-header" id="headingResolved">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    Resolved Reports
                  </button>
                </h2>
                <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingResolved" data-bs-parent="#reportAccordion">
                  <div class="accordion-body">
                      <table class="table table-hover">
                        <tr>
                            <th>Report Number</th>
                            <th>User</th>
                            <th>Report Status</th>
                            <th>Summary</th>
                            <th>View Submission</th>
                            <th>Administrator Notes</th>
                        </tr>
                        {% for report in resolved_reports %}
                                <tr>
                                    <td>{{ report.id }}</td>
                                    <td>{{ report.username }}</td>
                                    <td>
                                        {% if report.status == 'new' %}
                                            New
                                        {% elif report.status == 'in_progress' %}
                                            In Progress
                                        {% endif %}
                                    </td>
                                    <td>{{ report }}</td>
                                    <td>
                                        <a href="{% url "login:submission" report.id %}">
                                            <button class="btn btn-outline-primary">
                                                View submission
                                            </button>
                                        </a>
                                    </td>
                                     <td>
                                        <form method="post" action="{% url 'login:update_notes' %}" class="notes-form">
                                            {% csrf_token %}
                                            <div class="flex-container">
                                                <input type="hidden" name="report_id" value="{{ report.id }}">
                                                <textarea class="form-control editable-notes" name="notes" rows="3">{{ report.notes }}</textarea>
                                                <button type="submit" class="btn btn-outline-success btn-sm mt-2" style="width: 100%">Save</button>
                                            </div>
                                        </form>

                                    </td>
                                </tr>
                        {% endfor %}
                    </table>
                  </div>
                </div>
              </div>
            </div>


        {% else %}
            <p>No new reports are available.</p>
        {% endif %}
    </div>

</body>
{% endblock %}

project-a-09-main/login/templates/login/home_page.html
{% extends "base.html" %}

{% load bootstrap5 %}
{% load bootstrap5 socialaccount %}
{% load static %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<style>
    body {
        background-color: #ffffff;
    }
    .uva-theme {
        color: #ffffff;
        background-color: #00214d;
        border-color: #ff8c00;
    }
    .login-container {
        max-width: 800px;
        margin: auto;
        padding: 40px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    .login-heading {
        text-align: center;
        margin-bottom: 20px;
    }
    .login-form {
        margin-top: 30px;
    }
    .login-button {
        margin-bottom: 10px;
    }
    .form-group {
        margin-bottom: 20px;
    }
</style>

<div class="container mt-3">
    <div class="login-container uva-theme text-center">
        <div style="position: relative; width: 100%; padding-top: 30%; margin-bottom: 30px;">
            <img src="{% static 'login/images/rotunda.jpg' %}" loading="lazy" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; object-fit: cover;" class="rounded-circle mx-auto d-block" alt="UVA Rotunda">
        </div>
        <h1 class="login-heading">UVA - Reportify</h1>
        <form action="{% url 'login:home' %}" method="post" class="login-form" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_full_name" class="form-label">Full Name</label>
                <input type="text" class="form-control" id="id_full_name" name="full_name">
            </div>
            <div class="form-group">
                <label for="id_incident_type" class="form-label">Incident Type</label>
                <select class="form-select" id="id_incident_type" name="incident_type">
                    {% for value, label in form.incident_type.field.choices %}
                    <option value="{{ value }}">{{ label }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="id_description" class="form-label">Description</label>
                <textarea class="form-control" id="id_description" name="description" rows="4"></textarea>
            </div>
            <div class="form-group">
                <label for="id_location" class="form-label">Location</label>
                <input type="text" class="form-control" id="id_location" name="location">
            </div>
            <div class="form-group">
                <label for="id_images" class="form-label">Images</label>
                <input type="file" class="form-control" id="id_images" name="images">
            </div>
            <div class="form-group">
                <label for="id_videos" class="form-label">Videos</label>
                <input type="file" class="form-control" id="id_videos" name="videos">
            </div>
            <button type="submit" class="btn btn-outline-light btn-block login-button">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

project-a-09-main/login/templates/login/login_page.html
{% extends "base.html" %}

{% load bootstrap5 %}
{% load bootstrap5 socialaccount %}
{% load static %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<style>
    body {
        background-color: #ffffff;
    }
    .uva-theme {
        color: #ffffff;
        background-color: #00214d;
        border-color: #ff8c00;
    }
    .login-container {
        max-width: 500px;
        margin: auto;
        padding: 40px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    .login-heading {
        text-align: center;
        margin-bottom: 20px;
    }
    .rotunda-image {
    width: 50vw;
    height: 50vw;
    }
    .login-form {
        margin-top: 30px;
    }
    .login-button {
        margin-bottom: 10px;
    }
</style>

<div class="container mt-3">
    <div class="login-container uva-theme text-center">
        <div style="position: relative; width: 100%; padding-top: 66.7%; margin-bottom: 30px;">
            <img src="{% static 'login/images/rotunda.jpg' %}" loading="lazy" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; object-fit: cover;" class="rounded-circle mx-auto d-block" alt="UVA Rotunda">
        </div>
        <h1 class="login-heading">UVA - Reportify</h1>
        <form action="{% url 'login:welcome' %}" method="post" class="login-form">
            {% csrf_token %}
            <div class="row mb-3">
                <div class="col">
                    <a href="{% url 'google_login' %}" class="btn btn-outline-light btn-block login-button">Google Login</a>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <button type="button" class="btn btn-outline-light btn-block login-button" onclick="window.location.href='{% url 'login:home' %}'">Continue as Guest</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

project-a-09-main/login/templates/login/view_reports.html
{% extends "base.html" %}

{% load bootstrap5 %}
{% load bootstrap5 socialaccount %}
{% load static %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<style>
    body {
        background-color: #ffffff;
    }
</style>

{% if user.is_authenticated %}
<div class="container mt-3">
    <h2>Report Submission History</h2>
    {% if user_reports %}
        <table class="table table-hover">
                <tr>
                    <th>Report Number</th>
                    <th>Resolved</th>
                    <th>Administrator Notes</th>
                    <th>Report Submission</th>
                </tr>
                {% for report in user_reports %}
                    <tr>
                        <td>{{ report.id }}</td>
                        <td>
                            {% if report.resolved %}
                                Yes
                            {% else %}
                                No
                            {% endif %}
                        </td>
                        <td> {{ report.notes }}</td>
                        <td>
                            <a href="{% url "login:submission" report.id %}">
                                <button class="btn btn-outline-primary">
                                    View submission
                                </button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
        </table>
    {% else %}
        <p>You haven't submitted any reports yet!</p>
    {% endif %}
</div>
{% endif %}
{% endblock %}

project-a-09-main/login/templates/login/view_submission.html
{% extends "base.html" %}

{% load bootstrap5 %}
{% load socialaccount %}

{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}

<body>
<div class="container my-5">
    <h1 class="text-center">View Report Submission</h1>
    <p class="text-center"><strong>Submitted by:</strong> {{ report.username }}</p>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <table class="table table-bordered">
                <tbody>
                <tr>
                    <th scope="row"><strong>Status</strong></th>
                    <td>
                        {% if report.status == 'new' %}
                        New
                        {% elif report.status == 'in_progress' %}
                        In Progress
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <th scope="row"><strong>Incident Type</strong></th>
                    <td>
                        {% if report.incident_type == "1" %}
                        Security Breach
                        {% elif report.incident_type == "2" %}
                        Physical Altercation
                        {% elif report.incident_type == "3" %}
                        Theft or Vandalism
                        {% elif report.incident_type == "4" %}
                        Harassment or Discrimination
                        {% elif report.incident_type == "5" %}
                        Accident or Injury
                        {% elif report.incident_type == "6" %}
                        Medical Emergency
                        {% elif report.incident_type == "7" %}
                        Fire or Hazardous Materials Incident
                        {% elif report.incident_type == "8" %}
                        Cybersecurity Incident
                        {% elif report.incident_type == "9" %}
                        Missing Person
                        {% elif report.incident_type == "10" %}
                        Suspicious Activity
                        {% else %}
                        Unknown
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <th scope="row"><strong>Resolved</strong></th>
                    <td>{{ report.resolved | yesno:"Yes,No" }}</td>
                </tr>
                <tr>
                    <th scope="row"><strong>Description</strong></th>
                    <td>{{ report.description }}</td>
                </tr>
                <tr>
                    <th scope="row"><strong>Location</strong></th>
                    <td>{{ report.location }}</td>
                </tr>
                <tr>
                    <th scope="row"><strong>Submission Date</strong></th>
                    <td>{{ report.submission_date }}</td>
                </tr>
                {% if report.images %}
                <tr>
                    <th scope="row"><strong>Image</strong></th>
                    <td><img src="{{ report.images.url }}" width="400" alt="file submitted with the report"></td>
                </tr>
                {% endif %}
                {% if report.videos %}
                <tr>
                    <th scope="row"><strong>File</strong></th>
                    <td><video controls width="400"><source src="{{ report.videos.url }}" type="video/mp4">Your browser does not support the video tag.</video></td>
                </tr>
                {% endif %}
                </tbody>
            </table>
            {% if is_admin and not report.resolved %}
            <div class="text-center mb-4">
                <a href="{% url 'login:resolve_report' report.id %}" class="btn btn-primary">
                    Resolve Report
                </a>
            </div>
            {% endif %}
            <div class="text-center">
                <a href="{% url 'login:home' %}" class="btn btn-primary">
                    Return to home screen
                </a>
            </div>
        </div>
    </div>
</div>
</body>

{% endblock %}

project-a-09-main/login/templates/login/welcome_page.html
{% extends "base.html" %}

{% load static %}
{% load bootstrap5 %}

{% block content %}
<style>
    body {
        background-color: #ffffff;
    }
    .welcome-container {
        color: #ffffff;
        background-color: #00214d;
        border-color: #ff8c00;
        max-width: 500px;
        margin: auto;
        padding: 40px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        text-align: center;
        transition: background-color 0.1s ease, border-color 0.1s ease;
    }
    .welcome-image {
        max-width: 420px;
        border-radius: 50%;
        margin-bottom: 20px;
    }
    .welcome-heading {
        margin-bottom: 20px;
    }
    .welcome-text {
        margin-top: 20px;
        margin-bottom: 30px;
    }
    .welcome-button {
        margin-bottom: 10px;
        background-color: #ff8c00;
        border-color: #00214d;
        color: #ffffff;
    }
    .welcome-button:hover {
        color: #00214d;
        background-color: #ffffff;
        border-color: #00214d;
    }
</style>

<div class="container mt-3">
  <div class="welcome-container text-center">
    <div style="position: relative; width: 100%; padding-top: 66.7%; margin-bottom: 30px;">
      <img src="{% static 'login/images/rotunda.jpg' %}" loading="lazy" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; object-fit: cover;" class="rounded-circle mx-auto d-block" alt="UVA Rotunda">
    </div>
    <h1 class="welcome-heading">Welcome to Reportify!</h1>
    <p class="welcome-text">Your one-stop platform for reporting and managing incidents efficiently.</p>
    {% if not user.is_authenticated %}
    <p>To continue, please log in.</p>
    <a href="{% url 'login:login' %}" class="btn btn-outline-light welcome-button">Login</a>
    {% else %}
    <p>Welcome back, {{ user.username }}!</p>
    <a href="{% url 'login:home' %}" class="btn btn-outline-light welcome-button">Report</a>
    {% endif %}
  </div>
</div>
{% endblock %}